### ISSUE TITLE
lbm: update etl documentation for gh-page

### ISSUE THREAD

**Issue by deniers** [geoadmin/config-vt-schema-lbm#112]
updated documentation (first version, running but not fully configured)
- [x] aeroway
- [x] aerodrome_label
- [x] area_name
- [x] boundary
- [x] place
- [x] building
- [x] building_ln
- [x] construct
- [x] landcover
- [x] landuse
- [x] mountain_peak
- [x] park
- [x] poi
- [x] spot_elevation
- [x] contour_line
- [x] transportation
- [x] transportation_name
- [x] water
- [x] waterway
- [x] water_name

**Comment by luis-suter** [comment]
@deniers completed documentation in swisstopo wiki, closing issue.
