### ISSUE TITLE
raster burn: worldwide and CH

### ISSUE THREAD

**Issue by deniers** [geoadmin/config-vt-schema-lbm#160]
raster burn is very good
issues:
- the opacity changes drastically from z16 to z17 (from normal to very transparent): should be smoother
- raster min_brightness, saturation, etc (to make the relief appear lighter) should not be burnt into the raster. these parameters should be applied in the styling. the reason for this sis that we will most likely use the same raster for the next national map series style with strong colors where we could use the same raster

**Comment by luis-suter** [comment]
In speaking with @deniers & cartography team, the raster burn is approved, but we will still coordinate some knowledge transfer on the process in the future.
