### ISSUE TITLE
omt clipped with CH: water name

### ISSUE THREAD

**Issue by deniers** [geoadmin/config-vt-schema-lbm#161]
the lines to label water_name are clipped at the CH-border. although this is technically correct and can be applied to all other OMT-data, for water_name it creates uggly labels for water bodies that are located on the border:
https://api.maptiler.com/maps/7a4e79ee-4d8e-41d5-9764-aef363a99415/?key=ikKb7yPjxvOQgGWH28nA#11.94/46.44047/6.61597

solution: do not clip water_name with CH-polygon but remove all water_name that intersect with CH-polygon

**Comment by luis-suter** [comment]
tileshrink bug fix in progress

**Comment by luis-suter** [comment]
To be submitted directly to @deniers
