### ISSUE TITLE
bgdi db cluster migration

### ISSUE THREAD

**Issue by ltclm** [geoadmin/config-vt-schema-lbm#194]
Hello Luis

We will soon migrate the bgdi database cluster to amazon rds with postgres 12 / postgis 3.
In order to make this migration as smooth as possible for the vectortiles pipeline we should change the db connection host from:
`10.220.5.87`
to
`pg.bgdi.ch`

The DB Migration will be done by the end of january. The DNS pg.bgdi.ch is already working, if you change the host ip to this dns the migration will be transparent for the vectortiles pipeline.
I think this has to be done on the worker instance too.
It may also be necessary to update the postgres-client on the worker instance.

Thank you for scheduling this feature request.
best regards
marcel

**Comment by luis-suter** [comment]
comment received, and passed on to appropriate personnel. Coordination meeting scheduled for early next week, and work likely to be done by @lazaa32.

Also coordinating some work in regard to tasks related to new National Map processing pipeline. 

Will be billed as part of VT maintenance budget.

**Comment by lazaa32** [comment]
Hi @ltclm,

the db connection must be changed in configuration file. I already tried to connect to database cluster with updated connection string and it worked without an issue. 
After updating the connection string in configuration file, the postgres container should be restarted. I would do that tonight to avoid any issues on your side.
Since the postgres container already runs postgres 12/postgis 3, I believe this is only modification which needs to be done.

**Comment by ltclm** [comment]
thanks @lazaa32 for the modifications and the feedback.
The cluster behind pg.bgdi.ch is still running postgres 9.4.26!
We have the kick off meeting for the database migration this later afternoon. 
I will inform you when i have the exact migration date and the date we will switch the dns.

**Comment by ltclm** [comment]
you can already switch the connection string and use the dns instead of the ip address.

**Comment by lazaa32** [comment]
Ok, I will modify the string tonight and restart the container.
Let me know once the cluster is migrated. I don't think it will effect import process as we use pg_dump/pg_restore but we can test it and keep an eye on the first import process after migration.

**Comment by ltclm** [comment]
Thank you!
which version of pg_dump/pg_restore are we using now?
i will tell you once we're ready!

**Comment by lazaa32** [comment]
We use 12.3 version
```
pg_dump (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)
pg_restore (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)
```
I didn't get to commit the changes and restart docker last night so I'll do it tonight.

**Comment by ltclm** [comment]
thanks, with this postgresql-client version we should be fine.
We will do the DNS switch next monday.
